on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform Format'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.3
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check